// Seed Data definition for CRDMS database seeding

export const seedUsers = [
  { username: 'admin', email: 'admin@crdms.com', password: 'adminpassword', role: 'Admin' },
  { username: 'hr_manager', email: 'hrmanager@crdms.com', password: 'hrpassword', role: 'HR Manager' },
  { username: 'recruiter', email: 'recruiter@crdms.com', password: 'recruiterpassword', role: 'Recruiter' },
  { username: 'interviewer', email: 'interviewer@crdms.com', password: 'interviewerpassword', role: 'Interviewer' },
  { username: 'data_entry', email: 'dataentry@crdms.com', password: 'dataentrypassword', role: 'Data Entry' },
  { username: 'viewer', email: 'viewer@crdms.com', password: 'viewerpassword', role: 'Viewer' }
];

export const seedCandidates = [
  {
    name: 'John Doe',
    email: 'john.doe@gmail.com',
    phone: '+91 98765 01234',
    skills: 'React, JavaScript, CSS, HTML5, Webpack, Redux',
    location: 'Mumbai',
    experience_years: 4.5,
    status: 'Applied',
    current_ctc: 950000,
    expected_ctc: 1200000,
    notice_period_days: 30,
    linkedin_url: 'https://www.linkedin.com/in/johndoe',
    company: 'Tech Solutions Ltd',
    preferred_location: 'Mumbai, Pune',
    remarks: 'Strong frontend profile, immediate joiner.',
    comment: 'HR screening completed.'
  },
  {
    name: 'Jane Smith',
    email: 'jane.smith@yahoo.com',
    phone: '+91 98765 56789',
    skills: 'Node.js, Express, MySQL, PostgreSQL, Redis, REST APIs, Docker',
    location: 'Bangalore',
    experience_years: 6.0,
    status: 'Interviewing',
    current_ctc: 1300000,
    expected_ctc: 1600000,
    notice_period_days: 60,
    linkedin_url: 'https://www.linkedin.com/in/janesmith',
    company: 'Innovate Systems',
    preferred_location: 'Bangalore, Remote',
    remarks: 'Strong backend skills, expects quick interviews.',
    comment: 'L1 technical round cleared.'
  },
  {
    name: 'Vijay Kumar',
    email: 'vijay.k@techcorp.in',
    phone: '+91 91234 56780',
    skills: 'React, Node.js, AWS, MongoDB, Docker, TypeScript, Jenkins',
    location: 'Delhi',
    experience_years: 3.2,
    status: 'Offered',
    current_ctc: 700000,
    expected_ctc: 1000000,
    notice_period_days: 15,
    linkedin_url: 'https://www.linkedin.com/in/vijaykumar',
    company: 'Delhi Devs',
    preferred_location: 'Delhi, Gurgaon',
    remarks: 'Offer letter dispatched on June 20th.',
    comment: 'Salary negotiations completed.'
  },
  {
    name: 'Sarah Jenkins',
    email: 'sarah.j@outlook.com',
    phone: '+44 20 7946 0912',
    skills: 'Python, Django, AWS, CI/CD, PostgreSQL, GraphQL',
    location: 'London',
    experience_years: 7.5,
    status: 'Hired',
    current_ctc: 6500000,
    expected_ctc: 7500000,
    notice_period_days: 90,
    linkedin_url: 'https://www.linkedin.com/in/sarahjenkins',
    company: 'Fintech UK',
    preferred_location: 'Remote',
    remarks: 'Hired for Senior Backend Engineer position.',
    comment: 'Background check completed successfully.'
  },
  {
    name: 'Carlos Mendez',
    email: 'carlos.m@devs.net',
    phone: '+52 55 1234 5678',
    skills: 'Java, Spring Boot, MySQL, Kubernetes, Microservices, JUnit',
    location: 'Pune',
    experience_years: 5.0,
    status: 'Screening',
    current_ctc: 1100000,
    expected_ctc: 1350000,
    notice_period_days: 0,
    linkedin_url: 'https://www.linkedin.com/in/carlosmendez',
    company: 'Global Tech Inc',
    preferred_location: 'Pune, Bangalore',
    remarks: 'Immediate joiner, resume matches requirements.',
    comment: 'L0 interview scheduled for tomorrow.'
  },
  {
    name: 'Emily Wong',
    email: 'emily.wong@consulting.org',
    phone: '+65 6789 0123',
    skills: 'Product Management, Agile, Scrum, Jira, Product Roadmap, Excel',
    location: 'Singapore',
    experience_years: 8.0,
    status: 'Rejected',
    current_ctc: 8000000,
    expected_ctc: 9000000,
    notice_period_days: 45,
    linkedin_url: 'https://www.linkedin.com/in/emilywong',
    company: 'Strategy Consulting',
    preferred_location: 'Singapore',
    remarks: 'Expected CTC exceeds standard bands.',
    comment: 'Rejected by Management during budget discussions.'
  }
];
